services:
  postgres:
    image: postgres:16
    container_name: paymentslab-postgres
    environment:
      POSTGRES_DB: paymentslab
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments -d paymentslab"]
      interval: 5s
      timeout: 5s
      retries: 10
