spring:
  application:
    name: payments-api

  datasource:
    url: jdbc:postgresql://localhost:5433/paymentslab
    username: payments
    password: payments

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

debug: false


logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
  level:
    root: WARN
    org.flywaydb: INFO
    org.flywaydb.core: INFO
    com.paymentslab: INFO
